app:
    resource: @AppBundle/Controller/
    type:     annotation

# OroUserBundle routes
_oro_user:
    resource: "@OroUserBundle/Resources/config/routing.yml"

_oro_project:
    resource: "@OroProjectBundle/Resources/config/routing.yml"

_oro_issue:
    resource: "@OroIssueBundle/Resources/config/routing.yml"