security:
    firewalls:
        secured_area:
            http_basic: ~
            provider: main
            form_login: false
            logout: false
            remember_me: false
            anonymous: true